name: Run SeaVision Script Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # This runs every 10 minutes
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python Seavision\ Data.py

    - name: Commit and push output file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add SeaVision_Data.geojson
        git commit -m "Update GeoJSON output"
        git push
